# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0002_juegosinflables'),
    ]

    operations = [
        migrations.RenameField(
            model_name='juegosinflables',
            old_name='name',
            new_name='duracion',
        ),
        migrations.RenameField(
            model_name='juegosinflables',
            old_name='contenido',
            new_name='indicaciones',
        ),
        migrations.AddField(
            model_name='juegosinflables',
            name='foto',
            field=models.ImageField(default=1, upload_to=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='juegosinflables',
            name='nombre',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='juegosinflables',
            name='precio',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
