# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 23:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0003_auto_20170626_2321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='juegosinflables',
            old_name='nombre',
            new_name='name',
        ),
    ]
