# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0004_auto_20170626_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juegosinflables',
            name='foto',
            field=models.ImageField(upload_to='photo'),
        ),
    ]
